image: "python:3.7"

.install-deps-template: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config settings.virtualenvs.in-project true
    - poetry install -vv

tests:
  <<: *install-deps
  stage: test
  script:
    - pytest --cov tests/
