cache:
  key: "pyklopp-${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - stage-quality
  - stage-tests

.install-deps-template: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv

.test-template: &test
  <<: *install-deps
  stage: stage-tests
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  script:
    - poetry run pytest tests/
  artifacts:
    paths:
      - tests/logs
    when: always
    expire_in: 1 week

# Test Jobs
test-python3.8:
  <<: *test
  image: python:3.8

test-python3.9:
  <<: *test
  image: python:3.9

test-python3.10:
  <<: *test
  image: python:3.10
