[tool.poetry]
name = "pyklopp"
version = "0.2.1"
description = ""
authors = [
    "Julian Stier <julian.stier@uni-passau.de>"
]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/innvariant/pyklopp"
repository = "https://github.com/innvariant/pyklopp"
documentation = "https://github.com/innvariant/pyklopp"

keywords = ["machine learning", "inference", "training"]

[tool.poetry.dependencies]
python = "^3.5"
cleo = "^0.7"
torch = ">=1.3"
torchvision = ">=0.4"
pytorch-ignite = "^0.2"
tqdm = "^4.40"
poetry-project = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
pyklopp = "pyklopp.console:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"